- name: Create a new droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: mydroplet
    oauth_token: '{{digital_ocean_auth_token}}' 
    size: 1gb
    region: sfo2
    image: ubuntu-16-04-x64
    wait_timeout: 500
    ssh_keys: ['{{ssh_key_fingerprint}}']
  register: my_droplet

- debug:
    msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
